# Generated by Django 5.2 on 2026-04-23 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OficinaOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_oficina', models.CharField(max_length=50, unique=True)),
                ('nombre_oficina_origen', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'oficina_org',
            },
        ),
        migrations.CreateModel(
            name='PoblacionCor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_punto', models.CharField(max_length=50, unique=True)),
                ('ciudad', models.CharField(max_length=200)),
                ('lat_ref', models.DecimalField(decimal_places=8, max_digits=12)),
                ('lon_ref', models.DecimalField(decimal_places=8, max_digits=12)),
            ],
            options={
                'db_table': 'poblacion_cor',
            },
        ),
        migrations.CreateModel(
            name='PriorityRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=50, unique=True)),
                ('priority_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'priorities_ref',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_route', models.CharField(max_length=50, unique=True)),
                ('origin', models.CharField(max_length=500)),
                ('destination', models.CharField(max_length=500)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('priority', models.IntegerField()),
                ('time_window_start', models.DateTimeField()),
                ('time_window_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('PENDING', 'Pending'), ('EXECUTED', 'Executed'), ('FAILED', 'Failed')], max_length=20)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('id_oficina', models.ForeignKey(blank=True, db_column='id_oficina', null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.oficinaorg', to_field='id_oficina')),
            ],
            options={
                'db_table': 'routes',
            },
        ),
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_time', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('SUCCESS', 'Success'), ('ERROR', 'Error')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='routes.route', to_field='id_route')),
            ],
            options={
                'db_table': 'execution_logs',
            },
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('origin', 'destination', 'time_window_start', 'time_window_end'), name='unique_route'),
        ),
    ]
